import { Ubuntu } from "next/font/google";
import Header from '@/components/HeaderComponents/header/header';
import '../assets/style/globals.scss'
import ScrollToTop from "@/components/scrollToTop/scrollToTop.jsx";

const ubuntu = Ubuntu({ subsets: ["latin"], weight: ['700'] });

export const metadata = {
  title: "Faculty Helper",
  description: "Generated by create next app",
  icons: {
    icon: "/logoFavicon.svg"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ubuntu.className}>
        <ScrollToTop />
        <Header />
        {children}
      </body>
    </html>
  );
}
